//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int ServiceLogId { get; set; }
        public Nullable<int> ServiceVersionId { get; set; }
        public string ExecutionStartTime { get; set; }
        public string ExecutionEndTime { get; set; }
        public string LogMessage { get; set; }
        public string AuditStatus { get; set; }
    
        public virtual ServiceVersion ServiceVersion { get; set; }
    }
}
