//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Similar
    {
        public int SimilarId { get; set; }
        public int ServiceId1 { get; set; }
        public int ServiceId2 { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
